[package]
name = "dterm"
version = "0.1.0"
edition = "2021"
default-run = "dterm"
authors = ["Troels Hoffmeyer <troels.d.hoffmeyer@gmail.com>"]
description = "Parser for Rust source code"
license = "MIT"
repository = "https://github.com/Troels51/dterm"
rust-version = "1.56"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui-tree-widget = "0.19"
zbus = { version = "3.14", default-features = false, features = ["tokio", "xml"] }
crossterm = "0.27"
tokio = { version = "1.32", features = ["full"] }
async-recursion = "1.0.4"
itertools = "0.11.0"
clap = { version = "4.4.1", features = ["derive"] }
ratatui = { version = "0.26.2", features = ["macros"] }
